/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

public class App {
    public String getGreeting() {
        return "Gradle project is worked!";
    }

    public static void main(String[] args) {
        System.err.println(new App().getGreeting());
    }
}
